version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.3-ce-git
    working-directory: /usr/src
    steps:
      - checkout
      - setup_remote_docker:
          docker_layout_caching: false
      - run:
          name: Build Docker Image
          command: |
            docker build -f Dockerfile.integration .